version: '{build}'
skip_tags: true
clone_depth: 2
environment:
  PYGMENTS_VERSION: '~> 1.2.0'
  matrix:
  # see https://www.appveyor.com/docs/linux-images-software/#ruby for list of installed Ruby runtimes
  - ruby_version: '26'
  - ruby_version: '23'
init:
- set PATH=C:\Ruby%ruby_version%\bin;%PATH:C:\Ruby193\bin;=%
- echo %PATH%
- ruby -v
- gem -v
- bundler --version
install:
- bundle --jobs=3 --path=.bundle\gems
build_script:
- bundle exec rake build
test_script:
- bundle exec rake spec
