require_relative 'core_ext/object'
require_relative 'core_ext/array'
require_relative 'core_ext/hash'
require_relative 'core_ext/numeric'
require_relative 'core_ext/string'
require_relative 'core_ext/regexp'
