= Breakable and Unbreakable Blocks
:description: By default, most blocks are breakable with anchor and caption orphan prevention. The unbreakable option prevents a block from breaking across pages.

Asciidoctor PDF gives the author some control over where content blocks are placed using the `unbreakable` and `breakable` options, and tries to provide sensible defaults when these options are not used.

If you want a block to be truly unbreakable, you add the `unbreakable` option.
If you want to prevent the orphaning of the anchor and title of a table or section, then you add the `breakable` option.
Otherwise, you don't need to specify either of these options.
This page goes into detail about what functionality these options enable.

[#default]
== Breakable by default

The following blocks are breakable by default.
This breakable behavior includes automatic anchor and caption orphan prevention.

* Admonitions
* Block images
* Code blocks (literal, listing, and source)
* Examples
* Open blocks
* Quote blocks
* Sidebars
* Verses

[.term]*Breakable with built-in anchor and caption orphan prevention* means that a block can break across pages, but the converter will automatically push the block to the next page, when necessary, to ensure a block's anchor and caption are kept with the block.

Tables and sections are breakable by default, but do not provide automatic anchor and caption orphan prevention.
For tables, that means the anchor and caption could be left on the current page if the table gets pushed to the next page.
For sections, that means the section's title may be left on the current page if the first content block doesn't fit.
However, you can turn on orphan prevention for tables and sections by adding the (seemingly redundant) `breakable` option as a hint.

[#breakable]
== Breakable option

Orphan prevention isn't applied to tables and sections by default.
The `breakable` option (which is merely intended as an author hint) can be applied to a table to ensure the anchor and caption are kept with the table if it gets advanced to the next page.

[,asciidoc]
----
.Optional table title
[#optional-id%breakable] <.>
|===
|Content |Content

|Content |Content
|===
----
<.> Assign the `breakable` option to a table, using the shorthand percent symbol (`%`) for the `option` attribute name, to indicate that the table's caption and anchor should be kept with the table.

The `breakable` option (which is merely indented as an author hint) can be applied to a section to ensure the title is kept with the first block of content if the first block gets advanced to the next page.

[,asciidoc]
----
[%breakable]
=== Title of a section

First block of content in the section.
----

You don't need to assign the `breakable` option any other block types because <<default,it is enabled by default>> and those other blocks already provide automatic anchor and caption orphan prevention.

.Why do I need to specify breakable if it's the default?
****
One of the challenges of AsciiDoc is that it's a mature language, and that means we have to be careful when introducing functionality not to break existing documents and toolchains.
Overloading the meaning of the `breakable` option is one such case.

Given that all blocks are breakable by default, there's no point in ever specifying the `breakable` option on the block for the purpose of making it breakable.
And since it's redundant, that provided an opportunity to use it as an author hint to mean something more without having to change the language.

When you add the `breakable` option to a block explicitly, the converter knows you placed it there.
That provides an opportunity to enable functionality that isn't enabled by default.
That extra behavior, in this case, is to keep the anchor and title with the first row of a table and the first block of a section.

The reason the `breakable` option has to be specified explicitly on tables and sections is because this computation comes at a slight cost in terms of performance and side effects.
It's minor, but it's there.
No other blocks require this.
****

[#unbreakable]
== Unbreakable option

When the `unbreakable` option is applied to a block, the converter will advance the block and its caption and anchor to the next page if it detects that the block is going to break across pages and it can fit on a single page.

[,asciidoc]
----
.Optional title of block
[%unbreakable] <.>
====
Content in an example block.

More content in an example block.
====
----
<.> Assign the `unbreakable` option to a block, using the shorthand percent symbol (`%`) for the `option` attribute name, to prevent the block from breaking across pages.

The `unbreakable` option can be assigned to individual blocks of the following types:

* Admonitions
* Block images
* Code blocks (literal, listing, and source)
* Examples
* Open blocks
* Quote blocks
* Sidebars
* Tables
* Verses

If a block with the `unbreakable` option is taller than a single page, it will not be advanced and, instead, break across pages.
In this case, the automatic orphan protection is still applied.

The converter does not honor the `unbreakable` option on all content blocks in AsciiDoc, such as lists and paragraphs.
In these cases, the author can elect to wrap the content in an open block with the `unbreakable` option.

[,asciidoc]
----
[%unbreakable]
--
If this paragraph does not fit in the remaining space on this page,
and it is short enough to fit on a page by itself,
the converter will advance it to the next page so it does not break.
--
----

Internally, the open block enclosure is exactly how `unbreakable` is supported on tables.

[#dry-run-performance]
.Why can't I assign unbreakable globally? Why don't sections and tables have orphan prevention by default?
****
The logic in the converter that calculates the extent of a block, which includes its title, main content, and padding, uses multiple passes, called "`dry runs`", to get an accurate measurement of where a block begins, ends, and whether it breaks across pages.
When the converter determines that a block's caption and anchor would be orphaned, or that a block breaks when it's marked as unbreakable, it has to advance to the next page and convert it again in order to redo the extent calculation.
This logic is vital for decorating the block with a border and background because the extent must be pixel accurate.
All these dry runs add additional processing time and effort to the conversion.

Making all blocks unbreakable by default adds a lot of extra steps (not to mention leaving behind a lot of gaps in the document).
Orphan prevents adds almost as many since it's a similar process.
Doing that by default for tables and sections would be too complex and costly.
To recoup some of the processing time, we decided to make some trade-offs.
Therefore, blocks are breakable by default and authors must opt-in to get orphan prevention for tables and sections.
****
