= Fonts
:url-cjk-gothic: https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic

== Support for non-Latin languages

Asciidoctor can process the full range of characters in the UTF-8 character set.
That means you can write your document in any language, save the file with UTF-8 encoding (_that's important!_), and expect Asciidoctor to convert the text properly.
But you still need a font that provides the glyphs for those characters.

When converting a document with Asciidoctor PDF, you may notice that some glyphs for certain languages, such as Chinese, are missing from the PDF.
PDF is a "`bring your own font`" kind of system.
In other words, the font you provide must provide glyphs for all the characters used.
There's no one font that supports all the world's languages (though some, like Noto Serif, certainly come close).
Even if there were such a font, bundling that font with the main gem would make it enormous.
It would also severely limit the style choices in the default theme, which targets Latin-based languages.
Therefore, we're taking the strategy of creating separate dedicated theme gems that target each language family, such as CJK.
Read on to find out how to use these themes.

Asciidoctor PDF provides a built-in theme that provides a broad range of characters in the CJK charsets, so you can start with that theme:

 $ asciidoctor-pdf -a scripts=cjk -a pdf-theme=default-with-fallback-font document.adoc

Notice the `-a scripts=cjk` option.
That's important.
It tells the converter to insert break opportunities between CJK characters so that the line wraps properly when mixing English and a CJK language like Japanese.

If the built-in theme with the fallback font doesn't go far enough, you'll need to use a theme that is optimized for CJK text.
You can get such a theme by installing the `asciidoctor-pdf-cjk-kai_gen_gothic` gem.
The {url-cjk-gothic}[asciidoctor-pdf-cjk-kai_gen_gothic^] project provides themes optimized for CJK languages based on the kai_gen_gothic font.
See the {url-cjk-gothic}/blob/master/README.md[asciidoctor-pdf-cjk-kai_gen_gothic project README^] for detailed setup instructions.

WARNING: The theme provided by the `asciidoctor-pdf-cjk-kai_gen_gothic` gem isn't compatible with Asciidoctor PDF {page-component-display-version}.
However, you can still use it to create a xref:theme:cjk.adoc[custom CJK theme].

Once you have that gem installed (and the fonts), you need to tell Asciidoctor PDF to use one of the themes.
If you're converting a document that is primarily written in Japanese, you'd run Asciidoctor PDF as follows:

 asciidoctor-pdf -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-theme=KaiGenGothicJP document.adoc

If that command fails, you may have better luck creating your own CJK theme.
