= Asciidoctor PDF Documentation

Asciidoctor PDF is a native PDF converter for AsciiDoc.
It bypasses the requirement to generate an intermediary format such as DocBook, Apache FO, or LaTeX.
Instead, you can use Asciidoctor PDF to convert your documents directly from AsciiDoc to PDF.
Its aim is to take the pain out of creating PDF documents from AsciiDoc.

[NOTE]
====
You're viewing the documentation for Asciidoctor PDF {page-component-display-version}.
If you're looking for the documentation for a previous release line, refer to one of the following repository branches:

* {url-project-repo}/tree/v1.6.x#readme[Asciidoctor PDF 1.6.x^]
* {url-project-repo}/tree/v1.5.x#readme[Asciidoctor PDF 1.5.x^]
====

== Overview

Asciidoctor PDF converts an AsciiDoc document directly to a PDF document.
The style and layout of the PDF is controlled by a dedicated theme file.
To the degree possible, Asciidoctor PDF supports all the features of AsciiDoc that are supported by Asciidoctor.
It also provides xref:features.adoc[additional PDF-specific features].
However, there are xref:features.adoc#limitations[certain limits] imposed by the PDF format and the underlying PDF library this extension uses.

Asciidoctor PDF uses the Prawn gem and Prawn's extensions, such as prawn-svg and prawn-table, to generate a PDF document.
{url-prawn}[Prawn^] is a general purpose PDF generator for Ruby that features high-level APIs for common needs like setting up the page and inserting images and low-level APIs for positioning and rendering text and graphics.

