= Inline Images

== Inline image sizing

Inline images can be sized in much the same way as block images, using the `pdfwidth`, `scaledwidth`, or `width` attributes, with the following exceptions:

* The viewport width unit (i.e., vw) is not recognized in this context.
* The image will be scaled down, if necessary, to fit the width and height of the content area.
* Inline images do not currently support a default width controlled from the theme.

To confine the inline image to the height of the line while preserving the aspect ratio, use the attribute `fit=line`.
If you want to prevent the inline image from being fit to the content area, such as in a normal table cell, use `fit=none`.

If the resolved height of the image is less than or equal to 1.5 times the line height, the image won't disrupt the line height and is centered vertically in the line.
This is done to maximize the use of available space.
Once the resolved height exceeds this amount, the height of the line is increased (by increasing the font size of the invisible placeholder text) to accommodate the image.
In this case, the surrounding text will be aligned to the bottom of the image.
If the image height exceeds the height of the page, the image will be scaled down to fit on a single page (this may cause the image to advance to the subsequent page).
