= Page Numbers
:description: By default, Asciidoctor PDF assigns the page number 1 to the first body page of a document and increments the page number for each page thereafter.

Asciidoctor PDF automatically keeps track of page numbers.
These page numbers determine the folio placement of each page.

== Default page number assignment

include::theme:page$page-numbers.adoc[tag=default]

It's possible to influence the virtual page numbering, the folio placement, and where page numbers are displayed using a combination of theme keys and document attributes.
See xref:theme:page-numbers.adoc[] to learn more.

== Printing page ranges

The print dialog doesn't understand the page numbers that are displayed in the running content.
The print dialog only considers physical pages.
Therefore, to print a range of pages as they are labeled in the document, you need to add the number of front matter pages (i.e., the non-numbered pages) to the page number range in the print dialog.

For example, if you only want to print the first 5 pages labeled with a page number (e.g., 1-5), and there are 2 pages before the page labeled as page 1, you need to add 2 to both numbers in the range, giving you a physical page range of 3-7.
That's the range you need to enter into the print dialog.
