= What's New in Asciidoctor PDF {page-component-version}
:description: The new features and fixes available in Asciidoctor PDF {page-component-version}.
:navtitle: What's New
:doctype: book
:leveloffset: 1
:page-toclevels: 2
:url-milestone-2-1-0: {url-project-issues}?q=is%3Aissue+milestone%3Av2.1.0+is%3Aclosed

This page presents the changes made in each of the patch releases in the Asciidoctor PDF {page-component-version} release line.
The releases are ordered from newest to oldest.

= Asciidoctor PDF {page-component-version}.0

_**Release date:** 2022.06.10 | *Release notes:* {url-project-repo}/releases/tag/v2.1.0[v{page-component-version}.0^] | *Issue label:* {url-milestone-2-1-0}[{page-component-version}.0^]_

Asciidoctor PDF {page-component-version} introduces several enhancements.
For a complete list of changes, see the {url-project-repo}/blob/main/CHANGELOG.adoc[CHANGELOG^].

== Page columns

The body of an article or manpage document can now be arranged into columns when the `page-columns` key is set in the theme.
The width of the gap between the columns can be adjusted with the `page-column-gap` key.
See xref:theme:page.adoc#columns[Columns] for more information.

== Other enhancements

* When `avoid` is assigned to the xref:theme:heading.adoc#part[heading-part-break-after key] in theme, a page break isn't inserted between a part and its first chapter.
* Support for the xref:image-scaling.adoc#width-attributes[scale attribute] was added to image macros.
* Support for the `iw` unit value was added to the xref:image-scaling.adoc#pdfwidth[pdfwidth attribute] on image macros.
* A backlink is created from a bibref on a bibliography entry to the first reference to that entry in the document.
* The text formatting on index term in the index section is preserved.

NOTE: Go to xref:2.0@whats-new.adoc[What's New in Asciidoctor PDF 2.0] to learn about all the new features, improvements, and fixes introduced in 2.0.
