= What's New in Asciidoctor PDF {page-component-version}
:description: The new features and fixes available in Asciidoctor PDF {page-component-version}.
:navtitle: What's New
:doctype: book
:leveloffset: 1
:page-toclevels: 2
:url-issue-label-2-3-0: {url-project-issues}?q=is%3Aissue+milestone%3Av2.3.0+is%3Aclosed

This page presents the changes made in each of the patch releases in the Asciidoctor PDF {page-component-version} release line.
The releases are ordered from newest to oldest.

= Asciidoctor PDF {page-component-version}.0

_**Release date:** 2022.08.16 | *Release notes:* {url-project-repo}/releases/tag/v2.3.0[v{page-component-version}.0^] | *Issue label:* {url-issue-label-2-3-0}[{page-component-version}.0^]_

Asciidoctor PDF {page-component-version}.0 introduces several enhancements and bug fixes.
For a complete list of changes, see the {url-project-repo}/blob/main/CHANGELOG.adoc[CHANGELOG^].

== Enhancements

* Place footnotes below last block of content, offset by the specified amount, when the `footnotes-margin-top` theme key is a fixed value (e.g. 0).
* Insert column break instead of page break in multi-column layout if `column` role is specified on the page break macro.
* Allow page or column break to be forced using `always` option (e.g., `[%always]`).
* Use a relative font size for big and small roles in the built-in themes.
* Use the default-for-print theme by default (no theme is specified) if media is `print` or `prepress`.
* Support text alignment roles on all styled paragraphs and verse blocks.

== Bug fixes

* Strip formatting added to source block by custom subs when syntax highlighter is enabled.
* Only indent text that starts at left margin (i.e., when text align is left or justify).
* Correctly compute height of heading and caption for orphan prevention.
* Honor theme settings (`prose-margin-inner` and `prose-text-indent-inner`) for inner paragraphs in abstract.
* Prevent footnote label from being split across lines.
* Keep footnote label with preceding adjacent text.

== Compliance

* Remove support for deprecated `spread` role on table.

== Previous releases

* See xref:2.2@whats-new.adoc[What's New in Asciidoctor PDF 2.2] to learn about the improvements added in Asciidoctor PDF 2.2.
* See xref:2.1@whats-new.adoc[What's New in Asciidoctor PDF 2.1] to learn about the improvements added in Asciidoctor PDF 2.1.
* Refer to xref:2.0@whats-new.adoc[What's New in Asciidoctor PDF 2.0] to learn about the new features, improvements, and fixes introduced in 2.0.
