= What's New in Asciidoctor PDF {page-component-version}
:description: The new features and fixes available in Asciidoctor PDF {page-component-version}.
:navtitle: What's New
:doctype: book
:leveloffset: 1
:page-toclevels: 2
:url-milestone-2-1-0: {url-project-issues}?q=is%3Aissue+milestone%3Av2.1.0+is%3Aclosed
:url-milestone-2-1-1: {url-project-issues}?q=is%3Aissue+milestone%3Av2.1.1+is%3Aclosed
:url-milestone-2-1-2: {url-project-issues}?q=is%3Aissue+milestone%3Av2.1.2+is%3Aclosed
:url-milestone-2-1-3: {url-project-issues}?q=is%3Aissue+milestone%3Av2.1.3+is%3Aclosed
:url-milestone-2-1-4: {url-project-issues}?q=is%3Aissue+milestone%3Av2.1.4+is%3Aclosed
:url-milestone-2-1-5: {url-project-issues}?q=is%3Aissue+milestone%3Av2.1.5+is%3Aclosed

This page presents the changes made in each of the patch releases in the Asciidoctor PDF {page-component-version} release line.
The releases are ordered from newest to oldest.

= Asciidoctor PDF {page-component-version}.5

_**Release date:** 2022.07.10 | *Release notes:* {url-project-repo}/releases/tag/v2.1.5[v{page-component-version}.5^] | *Issue label:* {url-milestone-2-1-5}[{page-component-version}.5^]_

== Bug fixes

* Fix position of background color on caption with outside margin.
* Don't allow font scale to compound when entering nested table.

= Asciidoctor PDF {page-component-version}.4

_**Release date:** 2022.06.26 | *Release notes:* {url-project-repo}/releases/tag/v2.1.4[v{page-component-version}.4^] | *Issue label:* {url-milestone-2-1-4}[{page-component-version}.4^]_

== Improvements

* Include source location in warning message for truncated table cell if sourcemap is enabled.

== Bug fixes

* Allow alt text for block image, video, and audio to wrap to next line on same page.
* Apply `text-transform` from custom role on phrase after attributes have been resolved.
* Make URL check more strict so image target containing a colon is not mistaken as a URL.

= Asciidoctor PDF {page-component-version}.3

_**Release date:** 2022.06.23 | *Release notes:* {url-project-repo}/releases/tag/v2.1.3[v{page-component-version}.3^] | *Issue label:* {url-milestone-2-1-3}[{page-component-version}.3^]_

== Bug fixes

* Interpret `start-at` theme keys with value `1` correctly (as `1` instead of `2`).
* Restore column layout after importing page(s) from PDF.
* Fix crash when border color is transparent (`thematic-break-border-color`, `admonition-column-rule`, `quote-border-color`, `verse-border-color`).
* Ensure page margin is restored after imported page.

= Asciidoctor PDF {page-component-version}.2

_**Release date:** 2022.06.17 | *Release notes:* {url-project-repo}/releases/tag/v2.1.2[v{page-component-version}.2^] | *Issue label:* {url-milestone-2-1-2}[{page-component-version}.2^]_

== Bug fixes

* Apply page layout from main document to new page in scratch document.
* Use correct logic to insert page before TOC with automatic placement when `doctype=book` and `media=prepress`.
* Use `get_entries_for_toc` to determine if the TOC is non-empty rather than `Document#sections?`.

= Asciidoctor PDF {page-component-version}.1

_**Release date:** 2022.06.14 | *Release notes:* {url-project-repo}/releases/tag/v2.1.1[v{page-component-version}.1^] | *Issue label:* {url-milestone-2-1-1}[{page-component-version}.1^]_

== Improvements

* Store zero-based column on `Extent` for extensions to use to position cursor at start of extent.

== Bug fixes

* Place block image in SVG format in correct column when `align` is `left` and page columns are enabled.
* Accurately trap LoadError from CodeRay if source language is not recognized on code block.
* Only draw rounded rectangle around phrase if `border-radius` is > 0.
* Use `base-border-color` value if border width is set on role for inline phrase but not border color.

= Asciidoctor PDF {page-component-version}.0

_**Release date:** 2022.06.10 | *Release notes:* {url-project-repo}/releases/tag/v2.1.0[v{page-component-version}.0^] | *Issue label:* {url-milestone-2-1-0}[{page-component-version}.0^]_

Asciidoctor PDF {page-component-version} introduces several enhancements.
For a complete list of changes, see the {url-project-repo}/blob/main/CHANGELOG.adoc[CHANGELOG^].

== Page columns

The body of an article or manpage document can now be arranged into columns when the `page-columns` key is set in the theme.
The width of the gap between the columns can be adjusted with the `page-column-gap` key.
See xref:theme:page.adoc#columns[Columns] for more information.

== Other enhancements

* When `avoid` is assigned to the xref:theme:heading.adoc#part[heading-part-break-after key] in theme, a page break isn't inserted between a part and its first chapter.
* Support for the xref:image-scaling.adoc#width-attributes[scale attribute] was added to image macros.
* Support for the `iw` unit value was added to the xref:image-scaling.adoc#pdfwidth[pdfwidth attribute] on image macros.
* A backlink is created from a bibref on a bibliography entry to the first reference to that entry in the document.
* The text formatting on index terms is preserved when displayed in the index section.

NOTE: Refer to xref:2.0@whats-new.adoc[What's New in Asciidoctor PDF 2.0] to learn about all the new features, improvements, and fixes introduced in 2.0.
