= Block and Caption Keys

[#block]
== block

The keys in the `block` category control the spacing below block elements when a more specific setting is not designated.
The bottom margin is only added if the block is followed by an adjacent block within the same enclosure (e.g., a sidebar, a table cell, or the area outside of any blocks).

.block keys
[#key-prefix-block,cols="3,4,5l"]
|===
|Key |Value Type |Example

//|padding
//|xref:measurement-units.adoc[Measurement] {vbar} <<measurement-units,Measurement[top,right,bottom,left]>>
//|block:
//  padding: [12, 15, 12, 15]

//|margin-top
//|xref:measurement-units.adoc[Measurement] +
//(default: 0)
//|block:
//margin-top: 6

|margin-bottom
|xref:measurement-units.adoc[Measurement] +
(default: 12)
|block:
margin-bottom: 6
|===

Block styles are applied to the following block types:

[cols="3*a",grid=none,frame=none]
|===
|
* admonition
* example
* quote
|
* verse
* sidebar
* image
|
* listing
* literal
* table
|===

[#caption]
== caption

The keys in the `caption` category control the arrangement and style of block captions.
In addition to the generic caption category, each of these keys (except for text decoration) can be set on the caption key nested inside the following block categories: blockquote, code (applies to literal, listing, and source blocks), example, footnotes, image, table, and verse.

.caption keys
[#key-prefix-caption,cols="3,4,5l"]
|===
|Key |Value Type |Example

|align^[1]^
|xref:text.adoc#align[Text alignment] +
(default: left)
|caption:
align: left

|font-color
|xref:color.adoc[Color] +
(default: _inherit_)
|caption:
font-color: #333333

|font-family
|xref:font.adoc[Font family name] +
(default: _inherit_)
|caption:
font-family: M+ 1mn

|font-kerning
|normal {vbar} none +
(default: _inherit_)
|caption:
font-kerning: none

|font-size
|xref:language.adoc#values[Number] +
(default: _inherit_)
|caption:
font-size: 11

|font-style
|xref:text.adoc#font-style[Font style] +
(default: italic)
|caption:
font-style: italic

|text-decoration
|xref:text.adoc#decoration[Text decoration] +
(default: none)
|caption:
text-decoration: line-through

|text-decoration-color
|xref:color.adoc[Color] +
(default: $caption-font-color)
|caption:
text-decoration-color: #ff0000

|text-decoration-width
|xref:language.adoc#values[Number] +
(default: $base-text-decoration-width)
|caption:
text-decoration-width: 0.5

|text-transform
|xref:text.adoc#transform[Text transform] +
(default: _inherit_)
|caption:
text-transform: uppercase

|margin-inside
|xref:measurement-units.adoc[Measurement] +
(default: 4)
|caption:
margin-inside: 3

|margin-outside
|xref:measurement-units.adoc[Measurement] +
(default: 0)
|caption:
margin-outside: 0
|===
1. When nested inside the `image` key (i.e., `image-caption-align`), the value `inherit` is also accepted.
The value `inherit` resolves to the alignment of the block image.
