= Block Image Category Keys
:navtitle: Block Image

The keys in this category control the arrangement of block images.

.image keys
[#key-prefix-image,cols="3,4,5l"]
|===
|Key |Value Type |Example

|align
|xref:image.adoc#align[Image alignment] +
(default: left)
|image:
align: left

|width^[1]^
|xref:measurement-units.adoc[Measurement] +
(default: _not set_)
|image:
width: 100%

|border-color^[2]^
|xref:color.adoc[Color] +
(default: _not set_)
|image:
border-color: #cccccc

|border-radius
|xref:language.adoc#values[Number] +
(default: _not set_)
|image:
border-radius: 2

|border-width^[2]^
|xref:language.adoc#values[Number] +
(default: _not set_)
|image:
border-width: 0.5

|border-fit^[3]^
|content {vbar} auto
(default: content)
|image:
border-fit: auto

3+|[#key-prefix-image-alt]*Key Prefix:* <<key-prefix-image-alt,image-alt>>

|content^[4]^
|xref:quoted-string.adoc[Quoted string] +
(default: "%\{link}[%\{alt}]%{/link} {vbar} %\{target}")
|image:
alt:
content: "%{alt} (%{target})"

|font-color
|xref:color.adoc[Color] +
(default: _inherit_)
|image:
alt:
font-color: #ff000

|font-family
|xref:font.adoc[Font family name] +
(default: _inherit_)
|image
alt:
font-family: Courier

|font-kerning
|normal {vbar} none +
(default: _inherit_)
|image:
alt:
font-kerning: none

|font-size
|xref:language.adoc#values[Number] +
(default: _inherit_)
|image:
alt:
font-size: 9

|font-style
|xref:text.adoc#font-style[Font style] +
(default: normal)
|image:
alt:
font-style: italic

3+|[#key-prefix-image-caption]*Key Prefix:* <<key-prefix-image-caption,image-caption>>

|caption-align
|xref:text.adoc#align[Text alignment] {vbar} inherit +
(default: $caption-align)
|image:
caption:
align: inherit

|caption-text-align
|xref:text.adoc#align[Text alignment] {vbar} inherit +
(default: $image-caption-align)
|image:
caption:
text-align: left

|caption-max-width^[5]^
|fit-content {vbar} fit-content(percentage) {vbar} none {vbar} xref:measurement-units.adoc[Measurement] +
(default: none)
|image:
caption:
max-width: fit-content
|===

1. Only applies to block images that don't have either a `pdfwidth` or `scaledwidth` attribute on the image macro.
If specified, this value takes precedence over the value of the `width` attribute on the image macro, but not over the value of the `pdfwidth` or `scaledwidth` attributes.
This key accepts the same values as the `pdfwidth` attribute.
2. The border is only used if a border color is specified, the border width is specified, the border width is greater than 0, and the `noborder` role is not present.
The border is drawn above the image on the inside of the box reserved for the image.
3. The value `auto` means the border should expand to fit the width of the container (i.e., full width) instead of the image.
4. Use the placeholders `%\{alt}`, `%\{target}`, `%\{link}`, and `%{/link}` to insert the alt text, image target, and link open/close tags into the content template.
5. In order for the image to be sized correctly when max-width is fit-content, a width should always be specified on the image.
