= Block Category Keys
:description: Reference list of the available global block category keys and their value types.
:navtitle: Block
:source-language: yaml

The keys in the `block` category control the anchor position and spacing below block elements when a more specific setting isn't designated.
Block styles are applied to the following block types:

[cols="2*a",width=75%,grid=none,frame=none]
|===
|
* admonition
* block image
* code (listing, literal, source)
* example
|
* quote
* sidebar
* table
* verse
|===

To control the spacing and indentation for paragraphs, see xref:prose.adoc[].

The bottom margin (`margin-bottom`) is only added if the block is followed by an adjacent block within the same enclosure (e.g., a sidebar, a table cell, or the area outside any blocks).

[cols="3,4,6a"]
|===
|Key |Value Type |Example

|anchor-top
|xref:measurement-units.adoc[Measurement] +
(default: `0`)
|[source]
block:
  anchor-top: -12

|margin-bottom
|xref:measurement-units.adoc[Measurement] +
(default: `12`)
|[source]
block:
  margin-bottom: 6
|===
