= Button Macro Category Keys
:description: Reference list of the available button UI macro category keys and their value types.
:navtitle: Button
:source-language: yaml

[#button]
== button

The keys in the `button` category apply to a button reference generated from the inline button macro.

[cols="3,4,6a"]
|===
|Key |Value Type |Example

|background-color
|xref:color.adoc[Color] +
(default: _not set_)
|[source]
button:
  background-color: #0000FF

|<<border-color,border-color>>
|xref:color.adoc[Color] +
(default: _not set_)
|[source]
button:
  border-color: #CCCCCC

|<<border-offset,border-offset>>
|xref:language.adoc#values[Number] +
(default: `0`)
|[source]
button:
  border-offset: 1.5

|border-radius
|xref:measurement-units.adoc[Measurement] +
(default: `0`)
|[source]
button:
  border-radius: 2

|border-width
|xref:measurement-units.adoc[Measurement] +
(default: `$base-border-width`)
|[source]
button:
  border-width: 0.5

|<<content,content>>
|xref:quoted-string.adoc[Quoted string] +
(default: `"%s"`)
|[source]
button:
  content: "[\u2009%s\u2009]"

|font-color
|xref:color.adoc[Color] +
(default: _inherit_)
|[source]
button:
  font-color: #FFFFFF

|font-family
|xref:font-support.adoc[Font family name] +
(default: `Courier`)
|[source]
button:
  font-family: M+ 1mn

|font-size
|xref:text.adoc#font-size[Font size] +
(default: _inherit_)
|[source]
button:
  font-size: 12

|font-style
|xref:text.adoc#font-style[Font style] +
(default: `bold`)
|[source]
button:
  font-style: normal
|===

[#border-color]
== border-color

A border is only applied to a button reference if the `border-color` key is specified and the `border-width` key isn't explicitly set to zero.

[#border-offset]
== border-offset

The border offset is the amount that the background and border swells around the button text.
The value assigned to `border-offset` doesn't affect the distance between the formatted button phrase and the phrases that surround it.

[#content]
== content

The character sequence `%s` assigned to the `content` key gets replaced with the button label.
