= Callout List and Number Category Keys
:navtitle: Callout List and Number
:source-language: yaml

[#callout-list]
== callout-list

The keys in the `callout-list` category control the arrangement and style of callout lists.

NOTE: The <<conum,conum category>> controls the appearance of the list markers (i.e., the callout numbers) in a callout list.
If you change the `font-size` setting on the callout list, then you likely need to change the `font-size` setting on the `conum` category as well.

[#key-prefix-callout-list,cols="3,4,5a"]
|===
|Key |Value Type |Example

|`font-color`
|xref:color.adoc[Color] +
(default: _inherit_)
|[source]
callout-list:
  font-color: '#555555'

|`font-family`
|xref:font-support.adoc[Font family name] +
(default: _inherit_)
|[source]
callout-list:
  font-family: M+ 1p

|`font-kerning`
|`normal` {vbar} `none` +
(default: _inherit_)
|[source]
callout-list:
  font-kerning: none

|`font-size`
|xref:language.adoc#values[Number] +
(default: _inherit_)
|[source]
callout-list:
  font-size: 9

|`font-style`
|xref:text.adoc#font-style[Font style] +
(default: _inherit_)
|[source]
callout-list:
  font-style: italic

|`item-spacing`
|xref:measurement-units.adoc[Measurement] +
(default: `$list-item-spacing`)
|[source]
callout-list:
  item-spacing: 3

|`line-height`
|xref:language.adoc#values[Number] +
(default: _inherit_)
|[source]
callout-list:
  line-height: 1

|`margin-top-after-code`
|xref:measurement-units.adoc[Measurement] +
(default: `-$block-margin-bottom`)
|[source]
callout-list:
  margin-top-after-code: 0

|`text-align`
|xref:text.adoc#align[Text alignment] +
(default: `$list-text-align`)
|[source]
callout-list:
  text-align: left

|`text-transform`
|xref:text.adoc#transform[Text transform] +
(default: _inherit_)
|[source]
callout-list:
  text-transform: lowercase
|===

[#conum]
== conum

The keys in the `conum` category control the style of callout numbers inside verbatim blocks and in callout lists.

[#key-prefix-conum,cols="3,4,5l"]
|===
|Key |Value Type |Example

|font-color
|xref:color.adoc[Color] +
(default: _inherit_)
|conum:
font-color: #b12146

|font-family^[1,2]^
|xref:font-support.adoc[Font family name] +
(default: _inherit_)
|conum:
font-family: M+ 1mn

|font-kerning^[2]^
|normal {vbar} none +
(default: _inherit_)
|conum:
font-kerning: none

|font-size^[2]^
|xref:language.adoc#values[Number] +
(default: _inherit_)
|conum:
font-size: $base-font-size

|font-style^[2]^
|xref:text.adoc#font-style[Font style] +
(default: _inherit_)
|conum:
font-style: normal

|line-height^[2]^
|xref:language.adoc#values[Number] +
(default: 1.15)
|conum:
line-height: 4 / 3

|glyphs^[3]^
|circled {vbar} filled {vbar} Unicode String ranges +
(default: circled)
|conum:
glyphs: \u0031-\u0039
|===
1. Currently, the font must contain the circle numbers starting at glyph U+2460.
2. font-family, font-kerning, font-size, font-style, and line-height are only used for markers in a colist.
These properties are inherited for conums inside a verbatim block.
3. The font must provide the required glyphs.
The glyphs can be specified as a comma-separated list of ranges, where the range values are Unicode numbers (e.g., \u2460).
Unicode escape sequences are recognized even if the value is not enclosed in double quotes.
