= Codespan Category Keys
:description: Reference list of the available codespan (inline monospace text in prose and table cells) category keys and their value types.
:navtitle: Codespan
:source-language: yaml

[#codespan]
== codespan

The keys in the `codespan` category are used for inline monospace text in prose and table cells.

[cols="3,4,6a"]
|===
|Key |Value Type |Example

|background-color
|xref:color.adoc[Color] +
(default: _not set_)
|[source]
codespan:
  background-color: #F5F5F5

|<<border-color,border-color>>
|xref:color.adoc[Color] +
(default: _not set_)
|[source]
codespan:
  border-color: #CCCCCC

|<<border-offset,border-offset>>
|xref:language.adoc#values[Number] +
(default: `0`)
|[source]
codespan:
  border-offset: 2

|border-radius
|xref:measurement-units.adoc[Measurement] +
(default: _not set_)
|[source]
codespan:
  border-radius: 3

|border-width
|xref:measurement-units.adoc[Measurement] +
(default: `$base-border-width`)
|[source]
codespan:
  border-width: 0.5

|font-color
|xref:color.adoc[Color] +
(default: _inherit_)
|[source]
codespan:
  font-color: #B12146

|font-family
|xref:font-support.adoc[Font family name] +
(default: `Courier`)
|[source]
codespan:
  font-family: M+ 1mn

|font-size
|<<font-size,Font size>> +
(default: _inherit_)
|[source]
codespan:
  font-size: 0.8em

|font-style
|xref:text.adoc#font-style[Font style] +
(default: _inherit_)
|[source]
codespan:
  font-style: bold
|===

[#border-color]
== border-color

A border is only drawn around a code phrase if the `border-color` key is specified and the `border-width` key isn't explicitly set to zero.
The border only works properly if the code phrase doesn't have nested formatting.
Otherwise, the border will be inherited, producing a less than desirable result.

[#border-offset]
== border-offset

The border offset is the amount that the background and border swells around the text.
It does not affect the distance between the formatted phrase and the phrases that surround it.

[#font-size]
== font-size

You're strongly encouraged to set the value of the `font-size` key to a relative font size using the `em` units (e.g., `0.9em`).
A code phrase with a fixed font size will not be scaled when the font size of the parent element (e.g., table, caption, etc.) is specified.
However, by using a relative value, the font size will be computed relative to the size of the text that surrounds it, giving you effectively the same result.
See xref:text.adoc#font-size[Font size] for more information about relative font sizes.
