= Description List Category Keys
:description: Reference list of the available description term and list category keys and their value types.
:navtitle: Description List
:source-language: yaml

[#description-list]
== description-list

The keys in the `description-list` category control the arrangement and style of description list terms and descriptions.

[cols="4,4,5a"]
|===
|Key |Value Type |Example

|description-indent
|xref:language.adoc#values[Number] +
(default: `30`)
|[source]
description-list:
  description-indent: 15

|term-font-color
|xref:color.adoc[Color] +
(default: _inherit_)
|[source]
description-list:
  term-font-color: #AA0000

|term-font-family
|xref:font-support.adoc[Font family name] +
(default: _inherit_)
|[source]
description-list:
  term-font-family: Noto Serif

|term-font-kerning
|`none` {vbar} `normal` +
(default: _inherit_)
|[source]
description-list:
  term-font-kerning: none

|term-font-size
|xref:language.adoc#values[Number] +
(default: _inherit_)
|[source]
description-list:
  term-font-size: 12

|term-font-style
|xref:text.adoc#font-style[Font style] +
(default: `bold`)
|[source]
description-list:
  term-font-style: italic

|term-line-height
|xref:language.adoc#values[Number] +
(default: `$base-line-height`)
|[source]
description-list:
  term-line-height: 1.2

|term-spacing
|xref:measurement-units.adoc[Measurement] +
(default: `4`)
|[source]
description-list:
  term-spacing: 5

|term-text-transform
|xref:text.adoc#transform[Text transform] +
(default: `none`)
|[source]
description-list:
  term-text-transform: smallcaps
|===

== Ordered and unordered description lists

Asciidoctor PDF supports unordered and ordered description lists.
These are defined as a description list, but displayed as an unordered or ordered description list with the term as a subject.
Only one term is supported.
The subject is shown using the term font style (bold by default).

By default, the subject is arranged as a run-in followed by a subject stop (`:` by default).

[source,asciidoc]
----
[unordered]
alpha:: partially complete and unstable
beta:: feature complete and undergoing testing
----

The subject stop can be customized using the `subject-stop` attribute.

[source,asciidoc]
----
[unordered,subject-stop=)]
alpha:: partially complete and unstable
beta:: feature complete and undergoing testing
----

If the `stack` role is present, the subject is stacked above the description.
In this case, the subject stop is only used if specified explicitly.

[source,asciidoc]
----
[unordered.stack]
alpha:: partially complete and unstable
beta:: feature complete and undergoing testing
----
