= Description List Category Keys
:navtitle: Description List

[#description-list]
== description-list

The keys in this category control the arrangement and style of definition list items (terms and descriptions).

[#key-prefix-description-list,cols="3,4,5l"]
|===
|Key |Value Type |Example

|term-font-color
|xref:color.adoc[Color] +
(default: _inherit_)
|description-list:
term-font-color: #AA0000

|term-font-family
|xref:font.adoc[Font family name] +
(default: _inherit_)
|description-list:
term-font-family: Noto Serif

|term-font-kerning
|normal {vbar} none +
(default: _inherit_)
|description-list:
term-font-kerning: none

|term-font-size
|xref:language.adoc#values[Number] +
(default: _inherit_)
|description-list:
term-font-size: 12

|term-font-style
|xref:text.adoc#font-style[Font style] +
(default: bold)
|description-list:
term-font-style: italic

|term-text-transform
|xref:text.adoc#transform[Text transform] +
(default: none)
|description-list:
term-text-transform: none

|term-line-height
|xref:language.adoc#values[Number] +
(default: $base-line-height)
|description-list:
term-line-height: 1.2

|term-spacing
|xref:measurement-units.adoc[Measurement] +
(default: 4)
|description-list:
term-spacing: 5

|description-indent
|xref:language.adoc#values[Number] +
(default: 30)
|description-list:
description-indent: 15
|===

== Ordered and unordered description lists

Asciidoctor PDF supports unordered and ordered description lists.
These are defined as a description list, but displayed as an unordered or ordered description list with the term as a subject.
Only one term is supported.
The subject is shown using the term font style (bold by default).

By default, the subject is arranged as a run-in followed by a subject stop (`:` by default).

[source,asciidoc]
----
[unordered]
alpha:: partially complete and unstable
beta:: feature complete and undergoing testing
----

The subject stop can be customized using the `subject-stop` attribute.

[source,asciidoc]
----
[unordered,subject-stop=)]
alpha:: partially complete and unstable
beta:: feature complete and undergoing testing
----

If the `stack` role is present, the subject is stacked above the description.
In this case, the subject stop is only used if specified explicitly.

[source,asciidoc]
----
[unordered.stack]
alpha:: partially complete and unstable
beta:: feature complete and undergoing testing
----
