= Footnotes Category Keys
:description: Reference list of the available footnotes category keys and their value types.
:navtitle: Footnotes
:source-language: yaml

The keys in the `footnotes` category control the style of the footnotes list at the end of a chapter (`book` doctype) or document (other doctypes).
The styling of the links is controlled by the xref:link.adoc[global link styles].
If the `footnotes-title` attribute is set in the document, its value will be used as the caption of the footnotes list.
As such, it will be styled as a xref:caption.adoc[block caption] and can also be configured independently of other captions.

[cols="3,4,5a"]
|===
|Key |Value Type |Example

|font-color
|xref:color.adoc[Color] +
(default: `$base-font-color`)
|[source]
footnotes:
  font-color: #CCCCCC

|font-size
|xref:text.adoc#font-size[Font size] +
(default: `9`)
|[source]
footnotes:
  font-size: 8

|font-style
|xref:text.adoc#font-style[Font style] +
(default: `$base-font-style`)
|[source]
footnotes:
  font-style: italic

|item-spacing
|xref:measurement-units.adoc[Measurement] +
(default: `3`)
|[source]
footnotes:
  item-spacing: 5

|margin-top
|xref:measurement-units.adoc[Measurement] +
(default: `0`)
|[source]
footnotes:
  margin-top: 2

|text-transform
|xref:text.adoc#transform[Text transform] +
(default: _inherit_)
|[source]
footnotes:
  text-transform: lowercase
|===
