= Keyboard Macro Category Keys
:description: Reference list of the available keyboard UI macro (kbd) category keys and their value types.
:navtitle: Keyboard
:source-language: yaml

[#kbd]
== kbd

The keys in the `kbd` category apply to a kbd reference generated from the inline keyboard macro.
The kbd reference is a span of text denoting textual user input from a keyboard, voice input, or other text entry device.

[cols="3,4,5a"]
|===
|Key |Value Type |Example

|background-color
|xref:color.adoc[Color] +
(default: _not set_)
|[source]
kbd:
  background-color: #FAFAFA

|<<border-color,border-color>>
|xref:color.adoc[Color] +
(default: _not set_)
|[source]
kbd:
  border-color: #CCCCCC

|<<offset,border-offset>>
|xref:language.adoc#values[Number] +
(default: `0`)
|[source]
kbd:
  border-offset: 1.5

|<<border-color,border-radius>>
|xref:measurement-units.adoc[Measurement] +
(default: `0`)
|[source]
kbd:
  border-radius: 2

|<<border-color,border-width>>
|xref:measurement-units.adoc[Measurement] +
(default: `$base-border-width`)
|[source]
kbd:
  border-width: 0.375

|font-color
|xref:color.adoc[Color] +
(default: _inherit_)
|[source]
kbd:
  font-color: #000

|font-family
|xref:font-support.adoc[Font family name] +
(default: `Courier`)
|[source]
kbd:
  font-family: $base-font-family

|font-size
|xref:text.adoc#font-size[Font size] +
(default: _inherit_)
|[source]
kbd:
  font-size: 10.5

|font-style
|xref:text.adoc#font-style[Font style] +
(default: `italic`)
|[source]
kbd:
  font-style: normal

|<<separator,separator>>
|xref:quoted-string.adoc[Quoted string] +
(default: `"+"`)
|[source]
kbd:
  separator: "\u2009+\u2009"
|===

[#border-color]
== border-color

A border is only applied to a kbd reference if the `border-color` key is specified and the `border-width` key isn't explicitly set to zero.

[#offset]
== border-offset

The border offset is the amount that the background and border swells around the keyboard sequence text.
The value assigned to `border-offset` doesn't affect the distance between the formatted keyboard sequence and the phrases that surround it.

[#separator]
== separator

The value of the `separator` key is only used for multi-key input sequences.
