= Prose Category Keys
:description: Reference list of the available prose category keys and their value types.
:navtitle: Prose (Paragraph Text)
:source-language: yaml

[#prose]
== prose

The keys in the `prose` category control the spacing below paragraphs (but not paragraphs in a normal table cell), lists, and index categories.
The bottom margin is only added if the block is followed by an adjacent block within the same enclosure (e.g., a sidebar, a table cell, or the area outside a block).

[cols="3,4,5a"]
|===
|Key |Value Type |Example

|margin-bottom
|xref:measurement-units.adoc[Measurement] +
(default: `12`)
|[source]
prose:
  margin-bottom: 6

|<<margin-inner,margin-inner>>
|xref:measurement-units.adoc[Measurement] +
(default: `$prose-margin-bottom`)
|[source]
prose:
  margin-inner: 0

|text-indent
|xref:measurement-units.adoc[Measurement] +
(default: _not set_)
|[source]
prose:
  text-indent: 18

|<<text-indent-inner,text-indent-inner>>
|xref:measurement-units.adoc[Measurement] +
(default: _not set_)
|[source]
prose:
  text-indent-inner: 18
|===

[#margin-inner]
== margin-inner

The `margin-inner` key controls the margin between adjacent paragraphs.
It's useful when using indented paragraphs.

[#text-indent-inner]
== text-indent-inner

The `text-indent-inner` key is only applied to inner paragraphs.
Inner paragraphs are paragraphs that follow an adjacent paragraph.
