= Text Styles

[#text-align]
== Text alignment

The `text-align` key is used to align text horizontally within the text box.
It has the same function as the `text-align` property in CSS.

The text can be aligned using the following keywords:

* `left`
* `center`
* `right`
* `justify` (flush to each edge of the text box, if possible)

The `text-align` key is distinct from the similarly-named `align` key.
The latter key aligns a block element horizontally within its container.

[#decoration]
== Decoration

The following decorations can be applied to text:

* `none` (no decoration)
* `underline`
* `line-through`

[#font-style]
== Font style

In most cases, wherever you can specify a custom font family, you can also specify a font style.
These two settings are combined to locate the font to use.

The following font styles are recognized:

* `normal` (no style)
* `italic`
* `bold`
* `bold_italic`

[#transform]
== Transform

Many places where font properties can be specified, a case transformation can be applied to the text.
The following transforms are recognized:

* `uppercase`
* `lowercase`
* `capitalize` (each word, like CSS)
* `none` (clears an inherited value)
